# Last updated 11/26/2022

runtime: php81 # Replace with php74 to use PHP 7.4

handlers:
- url: /imgs
  static_dir: imgs

- url: /upload
  static_dir: src/upload

- url: /css
  static_dir: src/css

- url: /js
  static_dir: src/js

# Serve images as static resources.
# - url: /(.+\.(gif|png|jpg|ico))$
#   static_files: \1
#   upload: .+\.(gif|png|jpg|ico)$

# Serve your app through a front controller at 
# index.html, index.php or public/index.php.
- url: .*
  script: auto

entrypoint:
  serve src/handler.php

# environment variables
  # REPLACE USER, PASSWORD, DATABASE, AND CONNECTION_NAME with 
  # the values obtained when configuring your Cloud SQL instance
env_variables:
  INSTANCE_UNIX_SOCKET: /cloudsql/webdev-370920:us-central1:mysql0
  CLOUDSQL_USER: root
  CLOUDSQL_PASSWORD: s([UJ7INhE<\Y9*r
  CLOUDSQL_DB: mydb
# [END gae_cloudsql_mysql_env]




